### PR TITLE
Added TONS of sites (about 343)

### PR DESCRIPTION
**Pull request by Kore-Development**
i wanted to help add more sites so i added about 343 sites that i know r dangerous

http://stopmodreposts.org/ is where i got the list (and i added adfly)

### CODE REVIEW

**Comment by Kore-Development** [comment]
if u want a pastebin https://pastebin.com/raw/Rj2usV3m

**Comment by devsnek** [comment]
I'm not in the business of rating the explicit content of websites. The point of this is to identify links on which clicking the url will directly expose information which can expose private information about them.

**Comment by Kore-Development** [comment]
https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/SITES.md for the site list i used some of it is malware

**Comment by Kore-Development** [comment]
its ok even though it took a long time

**Comment by Kore-Development** [comment]
even though it took a long time

**Comment by devsnek** [comment]
I'll accept a new pr containing just the sites which distribute malware, but idc about people redistributing minecraft mods.

**Pull request closed without merging**
